#!/usr/bin/env bash
# Script that creates the file "/var/run/myscript.pid" containing its PID, displays "To infinity and beyond" indefinitely, displays "I hate the kill command" when receiving a SIGTERM signal, displays "Y U no love me?!" when receiving a SIGINT signal and deletes the file "/var/run/myscript.pid" and terminates itself when receiving a SIGQUIT or SIGTERM signal
touch /var/run/myscript.pid
echo $$ > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT
while true; do
echo "To infinity and beyond"
sleep 2
done