#!/usr/bin/env bash
#This is a script that print the time for 12 hours and 59 minutes

i=0
j=1

while [ $i -le 12 ]
do
echo "Hour: $i"
while [ $j -le 59 ]
do
echo "$j"
j=$((j + 1))
done
i=$((i + 1))
j=1
done

